/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gameutil_GameUtil */

#ifndef _Included_gameutil_GameUtil
#define _Included_gameutil_GameUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gameutil_GameUtil
 * Method:    sgameUtil
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gameutil_GameUtil_sgameUtil
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
